### ISSUE TITLE
Weblate source string links wrong

### ISSUE THREAD

**Issue by comradekingu** [Vitexus/icinga_configurator#8]
https://hosted.weblate.org/translate/icinga-editor/translations/nb_NO/?checksum=ac779a00ed33e7f6 links to
https://github.com/VitexSoftware/Icinga-Editor/blob/master/stemplate.php#L20
Related to #7

**Comment by Vitexus** [comment]
The project was little bit dying. Thank you for new life :)
Please fix NO translation as you need.

**Comment by comradekingu** [comment]
This is one of the hardest projects to translate, not because of the difficulty, but because the source could do with fixes for most every string. Setting up https://docs.weblate.org/en/latest/admin/continuous.html would help a lot, because then it can be edited directly from Weblate. There are also many strings in Czech.

**Comment by Vitexus** [comment]
Ok. I'll kick all czech strings from translate keywords if somebody wish.

**Comment by comradekingu** [comment]
If you add "kingu" https://hosted.weblate.org/user/kingu/ as an admin here https://hosted.weblate.org/access/icinga-editor I can fix a bunch of things. Linking, screenshots, notifications, etc.

**Comment by Vitexus** [comment]
Kingu is King!
